### ISSUE TITLE
Shell Pole (2.4)

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#603]
I'm not sure if this was already suggested but basically in 2.4, it's almost impossible to get off of a pole w/ Shell. It is possible by spamming Z but you don't get the jump boost you'd get by jumping off of the pole and pressing Z constantly to get off is just weird.
It's annoying having to get off of a pole w/ a shell, so if this could be fixed I'd be partying.

**Comment by EmeraldLoc** [comment]
Yea this was fixed

**Comment by Bear64DX** [comment]
In 2.4? Nice

**Comment by EmeraldLoc** [comment]
I take everything I said back

**Comment by Bear64DX** [comment]
Homie?

**Comment by EmeraldLoc** [comment]
Fixed

**Comment by Bear64DX** [comment]
WOOOOOOOO

**Comment by Bear64DX** [comment]
Wait are you sure you fixed this? I just downloaded the latest 2.4 and it still happens.

**Comment by EmeraldLoc** [comment]
Haven't pushed the commit

**Comment by Bear64DX** [comment]
Ohhhhhh
