### ISSUE TITLE
Some Romhack levels don't skip the bowser intro?

### ISSUE THREAD

**Issue by Bear64DX** [EmeraldLoc/tag#811]
I was testing a level that replaced Bowser 2, and for some reason the intro didn't skip. The bowser intro still played and it looked like this: 
![image](https://github.com/EmeraldLoc/tag/assets/171458695/6d63f5cf-2b8b-41b1-9ebb-9f10d9857434)
If there's an actual bhv for the intro let me know. The interesting thing is that this isn't really a "bowser" level. It is in the code, but you actually fight Eyerok here, not Bowser. What's also funny is that the second bowser level I added doesn't have this intro bug.

**Comment by EmeraldLoc** [comment]
Love the "wait lemme report this" message. Yea npc's can still talk to mario, which isn't intended. DX adds dialog features that were missing, so I can recreate the dialogs instead.

**Comment by Bear64DX** [comment]
> Love the "wait lemme report this" message.

lol

**Comment by EmeraldLoc** [comment]
fixed

**Comment by Bear64DX** [comment]
YEAAAAAAAAAAAAH

**Comment by Bear64DX** [comment]
This wasn't fixed. The only thing different is that the dialog is gone. The cutscene still plays, which was the initial problem to begin with.
