### ISSUE TITLE
Slide Terrain Interferes With Spectators Hard Floors

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#907]
Pretty self explanatory

**Comment by EmeraldLoc** [comment]
?

**Comment by TheMan6900** [comment]
https://github.com/user-attachments/assets/efa9c545-75a3-4a97-b493-38848b9f8bb4

**Comment by EmeraldLoc** [comment]
Ok, upload it.

**Comment by TheMan6900** [comment]
> Ok, upload it.

💀

**Comment by EmeraldLoc** [comment]
Resolved as a side effect of removing it entirely

**Comment by TheMan6900** [comment]
Pretty sure this can also happen with the hard floors modifiers by itself so this isnt actually fixed
